### ISSUE TITLE
Image storage, S3

### ISSUE THREAD

**Issue by msabrina** [msabrina/ARTrade#1]
Hi there, 
I'm setting up my image upload storage with with S3. I'm able to upload the picture and append it to the page but I cant figure how to send it to storage. I'm using the following documentation for reference;

https://www.npmjs.com/package/multer-s3
https://gist.github.com/adon-at-work/26c8a8e0a1aee5ded03c
and Amazon documentation. 

@gittheking, @jasonseminara, @rapala61, @trevorpreston, @irwintsay

**Comment by rapala61** [comment]
close this please :)

**Comment by msabrina** [comment]
Not able to implement upload function.
