### ISSUE TITLE
Appending image url

### ISSUE THREAD

**Issue by msabrina** [msabrina/ARTrade#3]
Hi there, 

I'm trying to append an image url to a component. I have a fetch call that is posting the image to the db on submit but i'd also like it to append to a different component. The fetch call lives in the create post component who is a sibling of the component I'm trying to append it to. I tried moving the fetch post to app.jsx, setting the state and sending it down as a prop but that's not working either. I'm thinking that in the sibling component where I'm trying to render it I have to have a display map function, but this is tricky because that component is changing state. So i have to match the image_url to the fair id...

**Comment by msabrina** [comment]
@gittheking, @jasonseminara, @rapala61, @trevorpreston, @irwintsay

**Comment by trevorpreston** [comment]
queued

**Comment by msabrina** [comment]
@mgershowitz
